name: korkort_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  flutter_svg: ^2.0.9
  async: ^2.11.0
  audio_video_progress_bar: ^2.0.1
  gif_view: ^0.4.0
  animations: ^2.0.8
  path_provider: ^2.1.1
  path: ^1.8.3
  dio: ^5.3.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/gif/
    - assets/video/
    - assets/svg/
